### ISSUE TITLE
Command link doesn't work

### ISSUE THREAD

**Issue by raspbeguy** [thefinn93/signal-weechat#10]
Hi,
I seem to be unable to run the command link.
I use Weechat 1.9 on ArchLinux with OpenJDK 1.8. Here is exactly what I did:
```
cd ~/.weechat/python
wget https://raw.githubusercontent.com/thefinn93/signal-weechat/master/signal.py
```
Then in weechat:
```
/script load signal.py
/signal install
/signal link
```
The last is idling on the following message:
```
Preparing to link to a device...
```
How can I link the device ? Thanks.

**Comment by thefinn93** [comment]
Hey, thanks for trying this out. There's been a lot of difficult-to-track-down issues with this related to constraints in weechat and signal-cli. I can poke at it in a bit, but getting dbus to weechat communication setup sucks and it was unable to get it reliably working.

I haven't touched the codebase in several months, i'll spend some time reminding myself how it works later today and see if I can make any suggestions.

**Comment by raspbeguy** [comment]
If that can help, by configuring standalone version of signal-cli and running the daemon, I am almost able to use it in weechat. Only problem, can just send messages, doesn't display incoming messages :)

**Comment by captbuckrogers25** [comment]
Same issue.  

Weechat 2.0-dev, Xubuntu 17.04, OpenJDK-8 (from package in ubuntu repo)
Used script gotten by cloning project and copying into ~./.weechat/python/autoload/
Followed same steps as raspbeguy in Weechat.  Same result.

**Comment by tych0** [comment]
I'm gonna close this since we're on the signald branch now, and we don't have support for linking any more :)
