### ISSUE TITLE
error when sending via /smsg

### ISSUE THREAD

**Issue by captbuckrogers25** [thefinn93/signal-weechat#11]
On getting linked to an existing account via the signal-cli executable in a terminal ("$ ./signal-cli link"), I attempted to send a signal message in weechat using /smsg and got the following error:

python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/buck/.weechat/python/autoload/signal.py", line 115, in send
python: stdout/stderr:     getSignal().sendMessage(message, dbus.Array(signature="s"), number)
python: stdout/stderr:   File "/home/buck/.weechat/python/autoload/signal.py", line 105, in getSignal
python: stdout/stderr:     return bus.get_object('org.asamk.Signal', '/org/asamk/Signal')
python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
python: stdout/stderr:     follow_name_owner_changes=follow_name_owner_changes)
python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
python: stdout/stderr:     self._named_service = conn.activate_name_owner(bus_name)
python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
python: stdout/stderr:     self.start_service_by_name(bus_name)
python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/dbus/bus.py", line 278, in
start_service_by_name
python: stdout/stderr:     'su', (bus_name, flags)))
python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/dbus/connection.py", line 651,
in call_blocking
python: stdout/stderr:     message, timeout)
python: stdout/stderr: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.asamk.Signal was not provided by any .service files
python: error in function "send"

-Weechat 2.0-dev, Xubuntu 17.04, OpenJDK-8 (from package in ubuntu repo)
-Used script gotten by cloning project and copying into ~./.weechat/python/autoload/
-"/script load signal.py", "/signal install"

**Comment by thefinn93** [comment]
Sorry for leaving this for an *entire month*, i should have said something earlier: I was pretty busy in August, i'm hoping to start investigating this shortly. It looks DBus-related, and I'm hoping to phase out DBus entirely, but that's going to be dependent on some changes to signal-cli (starting with [#90](https://github.com/AsamK/signal-cli/pull/90))

**Comment by tych0** [comment]
I'm gonna close this since we're on the signald branch now.
