### ISSUE TITLE
Insecure handing of /tmp

### ISSUE THREAD

**Issue by Mic92** [thefinn93/signal-weechat#19]
There are several cases where this plugin creates files in `/tmp/` in an insecure way: https://github.com/thefinn93/signal-weechat/blob/74f7397fc62e7362d469130f9bdcdf1840ee6755/signal.py#L472 https://github.com/thefinn93/signal-weechat/blob/74f7397fc62e7362d469130f9bdcdf1840ee6755/signal.py#L448

The issue is if an attacker on the same system can create a symlink in `/tmp/` since it is world-writeable and therefore trick the plugin into writing to it: https://owasp.org/www-community/vulnerabilities/Insecure_Temporary_File

An attacker could even gain write-access to the signal-cli tarball and modify it during the update process.

The fix is to use python's tempfile module: https://docs.python.org/3.8/library/tempfile.html
This also takes care of deleting data after being used

**Comment by thefinn93** [comment]
Thanks for opening this. The main goal with this repo is to move to signald and merge the signald branch.

In the mea ntime, if you want to submit a PR for the tempfile fix to this branch, I'm happy to merge.

**Comment by tych0** [comment]
I'm gonna close this since we've moved to the signald branch.
