### ISSUE TITLE
/signal command does not handle incorrect number of arguments well

### ISSUE THREAD

**Issue by thefinn93** [thefinn93/signal-weechat#2]
Things that are currently not handled how they should be:

* [x] `/signal +12024561414` - no message, maybe could just open a buffer?
* [x] `/signal` - no arguments at all. Should show help or tell user to do `/help signal`
* [ ] `/signal omg lol` - not a real number, silently fails

**Comment by tych0** [comment]
I just removed the `/signal` command on the signald branch, since it didn't do anything, so I'm gonna close this.
