### ISSUE TITLE
/smsg Doesn't seem to do anything

### ISSUE THREAD

**Issue by heywoodlh** [thefinn93/signal-weechat#28]
I have been trying to send a message via `/smsg +1XXXYYYXXXX my message contents` in Weechat and nothing happens. I haven't found any relevant error logs in `~/.weechat/logs` to indicate why nothing is happening. 

If somebody sends me a message I get them and I am able to respond without an issue to the conversations when they appear in my buffer after someone sends me a message. Everything seems to work except composing and sending a new message with `/smsg`. 

I have Weechat running in a Docker container (the Dockerfile and relevant `run.sh` are [here](https://github.com/heywoodlh/dockerfiles/tree/master/weechat) in case you want to reference) and I have the signal.py plugin installed in the correct directory:

```bash
/weechat # ls -l /weechat/.weechat/python/signal.py 
-rw-r--r--    1 weechat  weechat      13578 Sep 17 00:12 /weechat/.weechat/python/signal.py
```

I have signald also running in a Docker container and that's what is running my back end. I don't see any relevant logs from signald either.

So, a couple of questions:
1. Is there a logfile I should specifically look at for error logs? I'm pretty sure I would have found it if there was an error, but still, maybe I missed it.
2. Any ideas on what I'm missing? Perhaps my Docker container is missing a dependency that signal-weechat relies on?

Thanks for any suggestions! :)

**Comment by tych0** [comment]
I think on master "/smsg" only accepts one argument, the number/contact to message; it should open the buffer (but not switch to it). Does that happen?

Logs will live in ~/.weechat/logs/signal.log.

**Comment by heywoodlh** [comment]
I don't see any logs appended to `~/.weechat/logs/signal.log` upon executing `/smsg +1XXXYYYXXXX` and the buffer doesn't open either.

Any other suggestions? I'm sure it's something screwy with my setup but I still am not sure what.

**Comment by Mic92** [comment]
Fixed in https://github.com/thefinn93/signal-weechat/pull/33
This commands works for me as shown. You need to login first as well.
