### ISSUE TITLE
Doesn't work in headless environments where (user) dbus doesn't exist

### ISSUE THREAD

**Issue by thefinn93** [thefinn93/signal-weechat#7]
signal-cli has [discussed having a scrapable output](https://github.com/AsamK/signal-cli/issues/40), perhaps using something like that? ideally signal-cli's daemon could write directly to the socket file that we hook in the weechat, requiring only one daemon, not multiple.

**Comment by tych0** [comment]
We're on the signald branch now, which works just fine.
